/*
 * Generated by dtrace(1M).
 */

#ifndef	_EXAMPLEPROVIDER_H
#define	_EXAMPLEPROVIDER_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define EXAMPLE_STABILITY "___dtrace_stability$Example$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define EXAMPLE_TYPEDEFS "___dtrace_typedefs$Example$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	EXAMPLE_MY_HELLO_WORLD() \
do { \
	__asm__ volatile(".reference " EXAMPLE_TYPEDEFS); \
	__dtrace_probe$Example$my_hello_world$v1(); \
	__asm__ volatile(".reference " EXAMPLE_STABILITY); \
} while (0)
#define	EXAMPLE_MY_HELLO_WORLD_ENABLED() \
	({ int _r = __dtrace_isenabled$Example$my_hello_world$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$Example$my_hello_world$v1(void);
extern int __dtrace_isenabled$Example$my_hello_world$v1(void);

#else

#define	EXAMPLE_MY_HELLO_WORLD() \
do { \
	} while (0)
#define	EXAMPLE_MY_HELLO_WORLD_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _EXAMPLEPROVIDER_H */
